{
 "title": "CPT-Aggregated report",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "measurement",
    "query": "regression1,regression2,regression3"
   }
  ]
 },
 "panels": [
  {
   "title": "Create task response time - ${measurement}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "import \"experimental\"\nimport \"experimental/polyline\"\nfrom(bucket: \"CPT\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\n  |> filter(fn: (r) => r[\"application\"] == \"CPT\")\n  |> filter(fn: (r) => r[\"transaction\"] == \"Create task\")  \n  |> filter(fn: (r) => r[\"statut\"] == \"all\")\n  |> filter(fn: (r) => r[\"_field\"] == \"avg\")\n  |> group(columns: [\"transaction\"], mode:\"by\")\n  |> polyline.rdp(epsilon: 1.5)\n  |> rename(columns: {_value: \"Creat Task - ${measurement}\"})"
    }
   ]
  },
  {
   "title": "CPU % usage on APP",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"CPT\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_user\")\n  |> filter(fn: (r) => r[\"host\"] == \"testapp\")\n  |> filter(fn: (r) => r[\"tag1\"] == \"${measurement}\")\n  |> filter(fn: (r) => r[\"cpu\"] == \"cpu-total\")\n  |> rename(columns: {_value: \"CPU-${measurement}\"})\n"
    }
   ]
  },
  {
   "title": "RAM on DB",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"CPT\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\")\n  |> filter(fn: (r) => r[\"_field\"] == \"active\")\n  |> filter(fn: (r) => r[\"tag1\"] == \"${measurement}\")\n  |> filter(fn: (r) => r[\"host\"] == \"testdb\")\n  |> rename(columns: {_value: \"RAM-${measurement}\"})"
    }
   ]
  },
  {
   "title": "Virtual Users Number",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"CPT\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"meanAT\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\n  |> rename(columns: {_value: \"VU number-${measurement}\"})"
    }
   ]
  },
  {
   "title": "Regression runs comparisson (ALIGNED) [NO ZOOM]",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "import \"experimental\"\nfrom(bucket: \"CPT\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\n  |> filter(fn: (r) => r[\"transaction\"] == \"Create task\")  \n  |> filter(fn: (r) => r[\"statut\"] == \"all\")\n  |> filter(fn: (r) => r[\"_field\"] == \"avg\")\n  |> rename(columns: {_value: \"Create Task response\"})"
    },
    {
     "query": "import \"experimental\"\nfrom(bucket: \"CPT\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"${measurement}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"meanAT\")\n  |> filter(fn: (r) => r[\"transaction\"] == \"internal\")\n  |> rename(columns: {_value: \"VU number\"})"
    },
    {
     "query": "from(bucket: \"CPT\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_user\")\n  |> filter(fn: (r) => r[\"host\"] == \"testapp\")\n  |> filter(fn: (r) => r[\"tag1\"] == \"${measurement}\")\n  |> filter(fn: (r) => r[\"cpu\"] == \"cpu-total\")\n  |> rename(columns: {_value: \"CPU\"})"
    },
    {
     "query": "from(bucket: \"CPT\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\")\n  |> filter(fn: (r) => r[\"_field\"] == \"active\")\n  |> filter(fn: (r) => r[\"tag1\"] == \"${measurement}\")\n  |> filter(fn: (r) => r[\"host\"] == \"testdb\")\n  |> rename(columns: {_value: \"RAM\"})"
    }
   ]
  }
 ]
}